# -*- coding: utf-8 -*-
"""python 1.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WzFvBUDjhnxmbv6ddQPw5GJkFKPkTm4B

###exercise:
"""

for x in [0, 1, 2]:
  pass
  nothing will print

for x in range(6):
  print(x)
else:
  print("Finally finished!")

"""###1.Loop through the items in the fruits list.

#### hint: looping
"""

fruits = ["apple", "banana", "cherry"]
 #write the statement
for x in fruits:
  print(x)

"""###2.Print i as long as i is less than 6.

#### hint:looping
"""



i = 0
 #write the statement
while i<6:
  print(i)
  i += 1



"""### 3.Print "Hello World if a is greater than b.

####hint: conditional statements
"""

a = 50
b = 10
 
#write the statement
if a>b:
  print("Hello World")

"""###4.Take a variable x and print "Even" if the number(x) is divisible by 2, otherwise print "Odd"."""

x=10
if x%2=0:
    print("Even")
elif x%2!=0:
    print("Odd")

"""###5.Take a variable y and print "Grade A" if y is greater than 90, "Grade B" if y is greater than 60 but less than or equal to 90 and "Grade F" Otherwise."""

y=70
if y>90:
    print("Grade A")
elif 60<y<=90:
    print("Grade B")
 else:
    print("Grade F")

"""###6. Write a for loop to print all the numbers between 10 and 50."""

for i in range(10,50):
    print(i)

"""###7.Write a for loop to print all the 0dd numbers between 50 and 100.

#### hint: use range with step.
"""

for i in range(50,100):
  if (i%2!=0):
    print(i)